### ISSUE TITLE
New Fakku layout causing issues

### ISSUE THREAD

**Issue by avluis** [csaki/FakkuDroid#5]
A new layout has been implemented on fakku.net (Read Online is in a new div container, and general items have been moved about on the website's template) which are causing the app to show no data for individual items.
This is causing the download and the reading features to fail as well.

**Comment by cybrox** [comment]
Don't worry, I'm sure Jake will publish the JSON API soon.
It was 'almost ready' last time I asked, must've been a year ago or something.

**Comment by csaki** [comment]
@cybrox Wow, the last time, I hear about the fakku json api was a year ago. 
One of the Fakku developers send me a beta json api, but it just worked one or two months, then they removed the rest service and I didn't hear anything more of the project. 

Pd.- It seems the issue is closed, but I'm going to wait one or two days for feedbacks.

**Comment by avluis** [comment]
That's correct. They did sort of teased it but the other dev just sort of gave up with it.
I was pestering Jacob the other day about it, just waiting on a reply.

**Comment by avluis** [comment]
Replaced by Hentoid.
